theme: minima
title: Developing my pharmaceutical modelling coding skills
author: Eva Sorensson
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I hope to create updates as I develop my skills in Python and R relating to pharmaceutical modelling.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  EvaSorensson # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
